sudo: required

services:
  - docker

language: node_js
node_js:
  - 'node'

before_install:
  - alias kansa='docker-compose
    -f config/docker-compose.base.yaml
    -f config/docker-compose.dev.yaml
    -p kansa'
  - kansa up --build -d
  - sleep 10 # allow time for postgres db init

install:
  - echo $(cd modules/shop/server && npm install) # Shop tests have dependencies
  - cd integration-tests
  - npm install

after_failure:
  - kansa logs

after_script:
  - kansa down
