version: '2'

# docker-compose base layer
#
# This config is not sufficient by itself; it's just the base layer.
# For full config, see also docker-compose.{dev,prod}.yaml

volumes:
  pgdata: null

services:
  proxy:
    build: ../proxy
    image: kansa-proxy
    links:
      - server
    entrypoint: >
      /bin/bash -c
      "envsubst '$$SERVER_NAME $$SSL_CERTIFICATE $$SSL_CERTIFICATE_KEY' < /nginx.conf.template
      > /usr/local/openresty/nginx/conf/nginx.conf &&
      /usr/local/openresty/bin/openresty -g 'daemon off;'"

  server:
    build: ../
    image: kansa-server
    entrypoint: ./wait-for-it.sh postgres:5432 -- npm start
    links:
      - kyyhky
      - postgres
      - tarra
      - tuohi
    expose:
      - '80'
    volumes:
      - ../config/kansa.yaml:/kansa.yaml:ro
      - ../config/siteselection/ballot-data.js:/ss-ballot-data.js:ro

  tarra:
    image: worldcon75devops/label-printer:0.3.0
    expose:
      - '80'

  tuohi:
    image: eeemeli/pdf-form-fill:0.2
    expose:
      - '3000'
    environment:
      PDF_TEMPLATE_DIR: /templates
    volumes:
      - ../config/siteselection/ballot.pdf:/templates/ss-ballot.pdf:ro

  kyyhky:
    build: ../kyyhky
    image: kansa-kyyhky
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - redis
    expose:
      - '80'
    volumes:
      - ../config/message-templates:/message-templates:ro

  redis:
    image: redis:4.0
    expose:
      - '6379'

  postgres:
    image: postgres:10.4
    environment:
      PGDATA: /pgdata
      PGUSER: admin
      POSTGRES_DB: api
      POSTGRES_USER: admin
    expose:
      - '5432'
    volumes:
      - pgdata:/pgdata
      - ../postgres/init/10-admin-init.sql:/docker-entrypoint-initdb.d/10-admin-init.sql:ro
      - ../postgres/init/20-kansa-init.sql:/docker-entrypoint-initdb.d/20-kansa-init.sql:ro
      - ../postgres/init/22-kansa-tables.sql:/docker-entrypoint-initdb.d/22-kansa-tables.sql:ro
      - ../postgres/init/25-day-passes.sql:/docker-entrypoint-initdb.d/25-day-passes.sql:ro
      - ../postgres/init/25-payments.sql:/docker-entrypoint-initdb.d/25-payments.sql:ro
      - ../postgres/init/25-public-data.sql:/docker-entrypoint-initdb.d/25-public-data.sql:ro
      - ../postgres/init/28-siteselection.sql:/docker-entrypoint-initdb.d/28-siteselection.sql:ro
      - ../config/database/membership-types.sql:/docker-entrypoint-initdb.d/29-membership-types.sql:ro
      - ../modules/hugo/database/init.sql:/docker-entrypoint-initdb.d/30-hugo-init.sql:ro
      - ../config/database/hugo-categories.sql:/docker-entrypoint-initdb.d/31-hugo-categories.sql:ro
      - ../modules/hugo/database/tables.sql:/docker-entrypoint-initdb.d/32-hugo-tables.sql:ro
      - ../modules/raami/database/init.sql:/docker-entrypoint-initdb.d/40-raami-init.sql:ro
      - ../modules/events/database/50-init.sql:/docker-entrypoint-initdb.d/50-event-init.sql:ro
      - ../modules/events/database/52-spaces.sql:/docker-entrypoint-initdb.d/52-event-spaces.sql:ro
      - ../modules/events/database/54-events.sql:/docker-entrypoint-initdb.d/54-event-events.sql:ro
      - ../modules/events/database/56-participants.sql:/docker-entrypoint-initdb.d/56-event-participants.sql:ro
      - ../modules/events/database/58-messages.sql:/docker-entrypoint-initdb.d/58-event-messages.sql:ro
      - ../modules/events/database/60-log.sql:/docker-entrypoint-initdb.d/60-event-log.sql:ro
