# A short alphanumeric identifier, used e.g. as the cookie name, and in some
# downloaded file names.
id: w75

# The name of your event/convention
name: Worldcon 75

# If true, adding mailing address details for a member requires an "upgrade"
# action that requires payment. If false, paper pubs may be added without any
# cost.
paid_paper_pubs: false

# Authentication configuration. Duration values should use suffixes to indicate
# units, e.g. "1d 3h" or "4w".
auth:
  # If an expired key is used for login, the key is reset and automatically
  # sent by email. Admin users are those with any administrative privileges.
  key_timeout:
    normal: 1y
    admin: 5d

  # After session timeout, a user is redirected to the sign-in page at their
  # next request.
  session_timeout: 5d
